language: php
sudo: false
php:
- 5.4
- 5.5
- 5.6
script:
- ./vendor/bin/php-cs-fixer fix --verbose --dry-run
- ./vendor/bin/phpunit --coverage-text
before_script:
- mkdir -p build/logs
- composer install
after_script:
- php vendor/bin/coveralls -v
#after_success:
#  - if  [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh generate-api.sh; fi
#env:
#  global:
#  - secure: 
